name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  ci-test:

    name: CI Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo npm install
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql db: final_project4
        postgresql user: postgres
        postgresql password: root
    - name: Migrate DB
      run: sudo npm run db:migrate
    - name: Run DB seed
      run: sudo npm run db:seed
    - name: Run test
      run: sudo npm test